eda1_data_jf<-read.table("household_power_consumption.txt",header=TRUE,sep=";")
eda1_data_jf$Date <- as.Date(eda1_data_jf$Date, format="%d/%m/%Y")
relevant_data <- subset(eda1_data_jf, subset=(Date >= "2007-02-01" & Date <= "2007-02-02"))
relevant_data$Global_active_power<-as.numeric(relevant_data$Global_active_power)
date_time <- paste(as.Date(relevant_data$Date), relevant_data$Time)
relevant_data$date_time_2 <- as.POSIXct(date_time)
plot(relevant_data$Global_active_power~relevant_data$date_time_2, type="l",ylab="Global Active Power (kilowatts)", xlab="")
dev.copy(png, file="plot2.png", height=480, width=480)
dev.off()

